services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: i_pod
      POSTGRES_PASSWORD: "lbrp4fVNsvRj9_dpb1H1THYx37SIpl0U"
    volumes:
      - i_pod_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "r-LxMa6oxCUS0xFWxGvnMMmwIzg5D_eq"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: i_pod_test
      POSTGRES_PASSWORD: "ZbMpSAu-0vRGbATtzi694g-29kIMR03k"
    volumes:
      - i_pod_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "V-pnZ6gCbmlymAdq48OBvOa_E6y6l7Ba"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  i_pod_data:
  i_pod_test_data:
