name: i_pod_server
description: Starting point for a Serverpod server.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  serverpod: 2.9.1
  meta: ^1.17.0
  google_generative_ai: ^0.3.0
  serverpod_auth_server: 2.9.1 # Make sure this matches your Serverpod version

dev_dependencies:
  lints: '>=3.0.0 <7.0.0'
  test: '^1.24.2'
  serverpod_test: 2.9.1

